name: CI Workflow

env:
  DOTNET_NOLOGO: true

on:
  workflow_call:
    inputs:
      project:
        description: The project to build
        required: true
        type: string
      test:
        description: Should run tests or not
        default: false
        type: boolean
      test-project:
        description: The test project
        type: string
      publish:
          description: Publish to nuget or not
          default: false
          type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with: { dotnet-version: 8.0.x }

      - name: Nerdbank.GitVersioning
        if: ${{ inputs.publish }}
        uses: dotnet/nbgv@v0.4.2
        id: nbgv
        with: { setAllVars: true }

      - name: Build
        working-directory: ${{ inputs.project }}
        run: dotnet build -c Release

      # - name: Test
      #   working-directory: ${{ inputs.project }}
      #   run: dotnet pack -c Release --no-restore --no-build

      - name: Pack
        if: ${{ inputs.publish }}
        working-directory: ${{ inputs.project }}
        run: dotnet pack -c Release --no-restore --no-build

      - name: Publish to NuGet
        if: ${{ inputs.publish }}
        working-directory: artifacts/src/package/release
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
          SOURCE_URL: https://api.nuget.org/v3/index.json
        run: |
          dotnet nuget push **/*.nupkg --skip-duplicate -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }}

      # todo create release
