name: Translate Publish

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - "src/Translate/version.json"
      - "src/Translate/*.cs"
      - "src/Translate/*.csproj"

jobs:
  publish:
    name: Translate Publish
    uses: panoukos41/Annular/.github/workflows/_ci.yaml@dev
    with:
      project: src/Translate
      publish: true
    secrets: inherit
