name: Translate Publish Workflow

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - "src/Translate/version.json"
      - "src/Translate/*.cs"
      - "src/Translate/*.csproj"

jobs:
  build:
    name: Build
    uses: panoukos41/Annular/.github/workflows/_ci.yaml@main
    with:
      project: src/Translate
      publish: true
