name: Translate Build

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]
    paths:
      - "src/Translate/version.json"
      - "src/Translate/*.cs"
      - "src/Translate/*.csproj"

jobs:
  build:
    name: Translate Build
    uses: panoukos41/Annular/.github/workflows/_ci.yaml@dev
    with:
      project: src/Translate
