name: Translate Publish Workflow

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/Translate/version.json"
      - "src/Translate/*.cs"
      - "src/Translate/*.csproj"

jobs:
  build:
    name: Build
    uses: panoukos41/Annular/.github/workflows/translate-build.yaml@main
    with:
      cache: true

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        with: 
          dotnet-version: 8.0.x
          cache: true

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifacts-id }}
          path: /src/artifacts
          merge-multiple: true

      - name: Pack
        working-directory: src/Translate
        run: dotnet pack -c Release --no-restore --no-build

      - name: Publish to NuGet
        working-directory: artifacts/src/package/release
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
          SOURCE_URL: https://api.nuget.org/v3/index.json
        run: |
          dotnet nuget push **/*.nupkg --skip-duplicate -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }}

      # todo: Create github release
      # - name: Github Release
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: "Translate v${{ env.NBGV_SemVer2 }}"
      #     release_name: "Translate v${{ env.NBGV_SemVer2 }}"